Shanoir issue#1190 center deletion limitation
fli-iam/shanoir-ng pull request #1193
Opened 2022-01-31 10:50 UTC by jcomedouteau

See issue on how to test

2022-02-08 15:50 UTC, michaelkain requested changes
Hi Jean-Come,
thank you for this PR. I have been thinking about it.
I would prefer an implementation, where we extend study_examination in MS Studies with a centerId, that we can check on that ID locally, before deleting a center. So MS Studies can delete or not a center as an independent microservice, even if MS Datasets is down.
On the other hand, as already done today, when we create an exam in MS Datasets, we already inform MS Studies about, AFTER the creation of the exam in the db.
I think this approach better respects the separation of concerns principle in a microservice architecture. Your solution will fail if MS Datasets is down, even if MS Studies is the master of the centers.
I hope this sounds logic, with kind regards,
Michael

2022-02-09 07:54 UTC, jcomedouteau commented
I understand, this is feasible I think, we just need to create another structure to hold these informations.
Thanks for the feedback !

2022-03-25 13:59 UTC, michaelkain commented on shanoir-ng-studies/src/main/java/org/shanoir/ng/center/service/CenterServiceImpl.java
> +		if (exams.isEmpty()) {
I think you mean: !exams.isEmpty()?

2022-03-30 09:45 UTC, jcomedouteau commented on shanoir-ng-studies/src/main/java/org/shanoir/ng/center/service/CenterServiceImpl.java
> +		if (exams.isEmpty()) {
Ouch, yes. It's corrected.

2022-03-30 15:51 UTC, michaelkain approved these changes

2022-04-01 07:14 UTC, merged