shanoir-issue#1317 dataset acquisition update
fli-iam/shanoir-ng pull request #1321
Opened 2022-05-24 07:58 UTC by jcomedouteau

How to test:
- Update a dataset acquisition as an expert, it works.

Closes #1317

2022-05-24 08:06 UTC, Nunien commented
@jcomedouteau test are failing

2022-05-24 08:07 UTC, jcomedouteau commented
Yep, I'm on it !

2022-05-24 13:45 UTC, Nunien requested changes

2022-05-24 13:45 UTC, Nunien commented on shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
> +	DatasetAcquisitionMapper datasetAcquisitionMapper;
This is not used, is it ?

2022-05-24 13:52 UTC, jcomedouteau commented on shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
> +	DatasetAcquisitionMapper datasetAcquisitionMapper;
It isn't, I removed it! :+1:

2022-05-24 14:53 UTC, jcomedouteau commented
Do you have the "admin" right on this study ?

2022-05-25 07:25 UTC, Nunien commented
@jcomedouteau I think you compare Longs with == , maybe try .equals() ?

2022-05-25 08:20 UTC, jcomedouteau commented
I don't get it, I removed this line and it still does not work. It seems that 
`return commService.hasRightOnStudy(dataset.getStudyId(), rightStr);
`
returns false..

2023-04-19 08:52 UTC, jcomedouteau commented
I'm closing this one as this is not relevant anymore.

2023-04-19 08:52 UTC, closed without merging