shanoir-issue#1316 Download dataset naming - special chars on windows
fli-iam/shanoir-ng pull request #1322
Opened 2022-05-24 08:50 UTC by jcomedouteau

How to test:
- rename a dataset, examination, subject with special chars (/!?^() etc..) and download one and multiple datasets.
- Check that it works on windows. 
Closes #1316

2022-05-24 14:01 UTC, Nunien requested changes

2022-05-24 14:01 UTC, Nunien commented on shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
> +	private static final char[] FORBIDDEN_FILENAME_CHARS = {'\\', '/', ':', '*', '?', '\"', '<', '>', '|'};
Is this used ?

2022-05-24 14:01 UTC, Nunien commented on shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
> +		datasetName = datasetName.replaceAll("[^a-zA-Z0-9\\.\\-]", "_");
what does it replace ?

2022-06-14 14:02 UTC, jcomedouteau commented on shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
> +	private static final char[] FORBIDDEN_FILENAME_CHARS = {'\\', '/', ':', '*', '?', '\"', '<', '>', '|'};
Not anymore, I'm removing it.

2022-06-15 08:35 UTC, jcomedouteau commented
I removed the useless line and added a test to check the code.

2022-08-31 14:09 UTC, julien-louis approved these changes

2022-08-31 14:09 UTC, merged