shanoir-issue#2081: Tag and Quality tab show message + html fixes
fli-iam/shanoir-ng pull request #2085
Opened 2024-02-19 14:28 UTC by pierrehenri-dauvergne

Go to study
Open **Quality tab**
The message changes if there are quality cards or not
_Before_: can check/uncheck the 'check at import'
_Now_: can't check/uncheck
Click on edit
_Before_: the tab disapeared
_Now_: the tab is displayed, the button 'apply now' is disabled, added an edit button to open the quality card's page

Open **Tags tab**
_Before_: if no tag exist, nothing appears on the page
_Now_: a title and a message saying no tags exist is displayed

2024-03-18 10:22 UTC, jcomedouteau commented
@pierrehenri-dauvergne, the "apply at import" change does not trigger the update button to be enabled.
I know this is a recurring problem on this page, but maybe let's not add one more !

Otherwise, it's cool !

2024-03-18 16:15 UTC, pierrehenri-dauvergne commented
@jcomedouteau we talked with Julien and changed a bit the approach. In study details, the edit button is to edit study-related fields (not quality card).
Now, if a user is in quality/tree/bids tab and click 'edit', the user will be redirected toward 'general' tab and quality/tree/bids tab will be greyed out.

2024-04-05 09:19 UTC, julien-louis requested changes

2024-04-05 09:19 UTC, julien-louis commented on shanoir-ng-front/src/app/quality-control/quality-control.component.html
> +<span class="subtitle">{{ message }}</span>
I think messages should be defined in the template when possible

```<span class="subtitle" *ngIf="qualityCards?.length > 0">...</span>```

2024-04-05 09:19 UTC, julien-louis commented on shanoir-ng-front/src/app/tags/tag.creator.component.html
> +<span class="subtitle">{{ message }}</span>
same

2024-04-11 12:42 UTC, julien-louis approved these changes

2024-04-11 12:42 UTC, merged