Files and executable folder changed in bootstrap.sh
fli-iam/shanoir-ng pull request #2306
Opened 2024-07-10 11:21 UTC by AxelCouturierCIBM

2024-07-10 12:11 UTC, michaelkain commented
Dear @AxelCouturierCIBM thank you a lot for your PR!
I have assigned Anthony to it, who is the original developer of the bootstrap.sh.
Please be aware, that today we publish already versioned docker images on GitHub,
so there might be no need anymore to compile within the bootstrap.sh, see here:
https://github.com/orgs/fli-iam/packages?repo_name=shanoir-ng
@a-ba maybe it might be interesting to share some aspects of shanoir-deploy?
With kind regards, Michael

2024-07-24 12:18 UTC, a-ba requested changes

2024-07-24 12:18 UTC, a-ba commented on bootstrap.sh
> +	mkdir -p /src/tmp/home
I would rather just put `mkdir -p tmp/home` here. The /src directory is inside the container (and mapped to the current directory with `-v "$PWD:/src"`), there is no point to create it outside the container (neither to force the user to put his sources into /src)

2024-07-24 12:18 UTC, a-ba commented on README.md
> +To deploy shanoir from scratch on a development machine you can just put the files in /src/ folder, launch the
disagree (see below)

2024-08-20 12:32 UTC, michaelkain commented
Hi @a-ba, I hope you are doing fine. Could you please give us an update? Thank you, Michael

2024-08-20 15:13 UTC, a-ba commented
I am still waiting for the requested changes

2024-11-13 13:53 UTC, closed without merging