shanoir-issue#2513: fix center edit in study details
fli-iam/shanoir-ng pull request #2522
Opened 2024-11-28 11:03 UTC by pierrehenri-dauvergne

Fix #2513 and #2520 

How to test:
Open a study with multiple center
Go to center tab
Edit > remove a center > update study > it should work

Another test:
Start import CT
At step 3, in center options, make sure it's only those of the study (check before and after removing a center from that study)

2024-12-09 13:00 UTC, julien-louis requested changes
Great job, I spotted a bug though : when editing a study, the center select box is empty (and I can't see the request finding center names being called)

2024-12-09 16:20 UTC, pierrehenri-dauvergne commented
> Great job, I spotted a bug though : when editing a study, the center select box is empty (and I can't see the request finding center names being called)

Fixed. I tested on qualif and seems OK to me.

2025-01-07 14:26 UTC, julien-louis requested changes

2025-01-07 14:26 UTC, julien-louis commented on docker-compose-dev-front.yml
> +    command: ng serve --host 0.0.0.0 --disable-host-check --poll 10000
this should be discussed

2025-01-07 14:26 UTC, julien-louis commented on shanoir-ng-front/src/app/centers/shared/center.service.ts
> +        console.log("getCentersNames");
oups

2025-01-07 14:26 UTC, julien-louis commented on shanoir-ng-front/src/app/studies/study/study.component.ts
> +            console.log("test");
oups

2025-01-07 14:26 UTC, julien-louis commented on shanoir-ng-front/src/app/studies/study/study.component.ts
> +        console.log("centerId : ", centerId);
logs

2025-01-30 14:14 UTC, julien-louis approved these changes

2025-01-30 14:14 UTC, merged