display processings and output datasets in study trees
fli-iam/shanoir-ng pull request #564
Opened 2020-10-06 08:23 UTC by Nunien

2020-10-06 13:58 UTC, jcomedouteau commented
Just correct the processing display name

2020-10-06 14:40 UTC, jcomedouteau commented on shanoir-ng-front/src/app/subjects/tree/subject-tree.component.html
> +                            <node *ngFor="let dataset of processing.outputDatasets" [label]="dataset.name" awesome="fas fa-brain" (labelClick)="showDatasetDetails(dataset.id)" class="dataset-node">
Don't re-use dataset variable name ?

2020-10-12 07:04 UTC, michaelkain requested changes
Hi Julien, we agreed on not again having big pull requests. Could you please split them?

2020-11-03 13:52 UTC, michaelkain commented
Hi Julien, could you please take care of the conflicts, that we can merge it for Thursday? Thank you, Michael

2020-11-03 13:58 UTC, Nunien commented
@michaelkain  Done !

2020-11-04 13:29 UTC, merged