Shanoir-issue#876 Update and use dcm2niix by default
fli-iam/shanoir-ng pull request #877
Opened 2021-03-22 10:10 UTC by jcomedouteau

- Update dcm2niix version
- Set dcm2niix as default + tooltip

2021-04-07 12:26 UTC, Nunien commented on shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
> +                this.studyCard.niftiConverter = converters.filter(element => element.name === 'dcm2niix')[0];
fails in edit mode, this.studyCard is undefined at this point. Anyway, you don't want to change the converter in edit mode, your dev is only for the create mode. So you must move that code to the initCreate() function :
* Just move one row up this.studyCard = new StudyCard(); (above this.fetchNiftiConverters();)
*  Add a .then to this.fetchNiftiConverters(); : 
    * this.fetchNiftiConverters().then(() => {   put your code here   });

2021-04-07 12:28 UTC, Nunien requested changes

2021-04-07 12:28 UTC, Nunien commented on shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
> +                this.studyCard.niftiConverter = converters.filter(element => element.name === 'dcm2niix')[0];
fails in edit mode, this.studyCard is undefined at this point. Anyway, you don't want to change the converter in edit mode, your dev is only for the create mode. So you must move that code to the initCreate() function :
* Just move one row up this.studyCard = new StudyCard(); (above this.fetchNiftiConverters();)
*  Add a .then to this.fetchNiftiConverters(); : 
    * this.fetchNiftiConverters().then(() => {   put your code here   });

2021-04-07 14:10 UTC, jcomedouteau commented
@Nunien Corrected, well seen :) !

2021-04-07 14:52 UTC, Nunien approved these changes

2021-04-07 14:53 UTC, merged

2021-04-20 08:13 UTC, ebannier2018 commented
Hi, Can you keep me posted on this issue ? What is the current dcm2niix version ? When was it updated ? 
I still have an issue with some data imported on Friday April 9th. What was the dcm2niix version then ? see my email from April 14th + data attached. 
Thanks in advance
Elise

2021-04-20 08:24 UTC, jcomedouteau commented
Hello Elise !

We have updated the dcm2niix version:
Chris Rorden's dcm2niiX version v1.0.20201102 

This converter is now used for new imports (since the 15th of April). For older data, it was an older version of dcm2niix which was in use.
For the moment we can't re-convert the existing data, but there is a pull request to resolve this. (It will allow to re-convert dataset by dataset with a specific converter)

Jean-Côme

2021-04-22 09:27 UTC, ebannier2018 commented
Thanks a lot Jean-Come. Too bad for the many imports from April 9th but it worked fine for today's import. 
Btw, there was a recent release of a 2021 version of dcm2niix : https://github.com/rordenlab/dcm2niix/releases
Maybe interesting to update for this one ?

2021-04-26 12:21 UTC, jcomedouteau commented
Elise,
I had not seen it yet, I'll update it then !

Jean-Côme